# Generated by Django 4.1.7 on 2023-03-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbiapp', '0002_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form',
        ),
    ]
