# Generated by Django 4.1.7 on 2023-03-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='meterial',
        ),
    ]
