# Generated by Django 4.1.7 on 2023-03-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_remove_form_meterial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='Forum',
        ),
    ]
