# Generated by Django 4.1.7 on 2023-03-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_rename_form_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='district',
            field=models.TextField(),
        ),
    ]
